GET http://127.0.0.1:8001/suppliersno
Accept: application/json

###
GET http://127.0.0.1:8001/test
Accept: application/json

###
POST http://127.0.0.1:8001/suppliers
Content-Type: application/json

{
    "name": "Supplier 1",
    "country": "India",
    "contract_terms": {"terms": "Sample terms"},
    "last_audit": "2025-01-10"
}


###
### GET request to example server
POST http://127.0.0.1:8000/suppliers





###